services:
  web:
    image: nginx:latest
    ports:
      - "3005:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - .:/app
    environment:
      TZ: Asia/Ho_Chi_Minh
  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - .:/app

  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: yourlsmysqldb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Ho_Chi_Minh
